
package services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param code
     * @return
     *     returns services.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://services/", className = "services.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://services/", className = "services.GetCompteResponse")
    @Action(input = "http://services/BanqueWS/getCompteRequest", output = "http://services/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToDhs", targetNamespace = "http://services/", className = "services.ConversionEuroToDhs")
    @ResponseWrapper(localName = "conversionEuroToDhsResponse", targetNamespace = "http://services/", className = "services.ConversionEuroToDhsResponse")
    @Action(input = "http://services/BanqueWS/conversionEuroToDhsRequest", output = "http://services/BanqueWS/conversionEuroToDhsResponse")
    public double conversionEuroToDhs(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<services.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://services/", className = "services.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://services/", className = "services.GetComptesResponse")
    @Action(input = "http://services/BanqueWS/getComptesRequest", output = "http://services/BanqueWS/getComptesResponse")
    public List<Compte> getComptes();

}
